name: CI

on:
  pull_request:
    branches: ['*']
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Prettier and ESLint Checks
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - shell: bash
        run: pnpm install
      - run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - shell: bash
        run: pnpm install

      - run: pnpm run typecheck
